<?php
defined('_JEXEC') or die;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
?>
<div class="xdecaro-scope">
  <div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?php echo Text::_('COM_XDECAROTASKS_TASKS'); ?></h1><a class="btn btn-primary" href="<?php echo Route::_('index.php?option=com_xdecarotasks&view=task'); ?>"><?php echo Text::_('COM_XDECAROTASKS_NEW_TASK'); ?></a></div>
  <form method="get" class="card card-body mb-3"><input type="hidden" name="option" value="com_xdecarotasks"><input type="hidden" name="view" value="tasks"><div class="row g-2"><div class="col-12 col-md"><input class="form-control" name="search" value="<?php echo htmlspecialchars((string) ($this->filters['search'] ?? ''), ENT_QUOTES, 'UTF-8'); ?>" placeholder="<?php echo Text::_('JSEARCH_FILTER'); ?>"></div><div class="col-6 col-md-2"><select class="form-select" name="status"><option value=""><?php echo Text::_('COM_XDECAROTASKS_ALL_STATUS'); ?></option><?php foreach (['open','in_progress','blocked','completed','cancelled'] as $v) : ?><option value="<?php echo $v; ?>" <?php echo (($this->filters['status'] ?? '') === $v) ? 'selected' : ''; ?>><?php echo Text::_('COM_XDECAROTASKS_STATUS_' . strtoupper($v)); ?></option><?php endforeach; ?></select></div><div class="col-6 col-md-2"><select class="form-select" name="priority"><option value=""><?php echo Text::_('COM_XDECAROTASKS_ALL_PRIORITIES'); ?></option><?php foreach (['low','normal','high','urgent'] as $v) : ?><option value="<?php echo $v; ?>" <?php echo (($this->filters['priority'] ?? '') === $v) ? 'selected' : ''; ?>><?php echo Text::_('COM_XDECAROTASKS_PRIORITY_' . strtoupper($v)); ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-auto"><button class="btn btn-secondary" type="submit"><?php echo Text::_('JFILTER'); ?></button></div></div></form>
  <div class="card"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo Text::_('COM_XDECAROTASKS_FIELD_TITLE'); ?></th><th><?php echo Text::_('COM_XDECAROTASKS_FIELD_STATUS'); ?></th><th><?php echo Text::_('COM_XDECAROTASKS_FIELD_PRIORITY'); ?></th><th><?php echo Text::_('COM_XDECAROTASKS_FIELD_DUE_AT'); ?></th><th><?php echo Text::_('COM_XDECAROTASKS_SOURCE'); ?></th></tr></thead><tbody><?php if (!$this->items) : ?><tr><td colspan="5" class="text-center text-body-secondary py-4"><?php echo Text::_('JGLOBAL_NO_MATCHING_RESULTS'); ?></td></tr><?php endif; ?><?php foreach ($this->items as $item) : ?><tr><td><a href="<?php echo Route::_('index.php?option=com_xdecarotasks&view=task&id=' . (int) $item['id']); ?>"><strong><?php echo htmlspecialchars((string) $item['title'], ENT_QUOTES, 'UTF-8'); ?></strong></a></td><td><span class="badge bg-secondary"><?php echo Text::_('COM_XDECAROTASKS_STATUS_' . strtoupper((string) $item['status'])); ?></span></td><td><?php echo Text::_('COM_XDECAROTASKS_PRIORITY_' . strtoupper((string) $item['priority'])); ?></td><td><?php echo htmlspecialchars((string) ($item['due_at'] ?? ''), ENT_QUOTES, 'UTF-8'); ?></td><td><small><?php echo htmlspecialchars(trim((string) ($item['source_component'] ?? '') . ' ' . (string) ($item['source_id'] ?? '')), ENT_QUOTES, 'UTF-8'); ?></small></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
