<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
$id = (int) ($this->task['id'] ?? 0);
?>
<div class="xdecaro-scope">
  <div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0"><?php echo $id ? htmlspecialchars((string) $this->task['title'], ENT_QUOTES, 'UTF-8') : Text::_('COM_XDECAROTASKS_NEW_TASK'); ?></h1><a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_xdecarotasks&view=tasks'); ?>"><?php echo Text::_('JLIB_HTML_BEHAVIOR_CLOSE'); ?></a></div>
  <form action="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.save'); ?>" method="post" class="card card-body mb-3"><div class="row g-3"><div class="col-12"><?php echo $this->form->renderField('title'); ?></div><div class="col-12"><?php echo $this->form->renderField('description'); ?></div><div class="col-12 col-md-4"><?php echo $this->form->renderField('status'); ?></div><div class="col-12 col-md-4"><?php echo $this->form->renderField('priority'); ?></div><div class="col-12 col-md-4"><?php echo $this->form->renderField('due_at'); ?></div><div class="col-12 col-md-4"><?php echo $this->form->renderField('recipient_type'); ?></div><div class="col-12 col-md-8"><?php echo $this->form->renderField('recipient_id'); ?></div></div><?php echo $this->form->getInput('id'); ?><?php echo HTMLHelper::_('form.token'); ?><div class="mt-3 d-flex gap-2"><button class="btn btn-primary" type="submit"><?php echo Text::_('JSAVE'); ?></button><?php if ($id && ($this->task['status'] ?? '') !== 'completed') : ?><button class="btn btn-success" formaction="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.complete&id=' . $id); ?>" type="submit"><?php echo Text::_('COM_XDECAROTASKS_COMPLETE'); ?></button><?php endif; ?><?php if ($id && ($this->task['status'] ?? '') !== 'cancelled') : ?><button class="btn btn-outline-danger" formaction="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.cancel&id=' . $id); ?>" type="submit"><?php echo Text::_('COM_XDECAROTASKS_CANCEL'); ?></button><?php endif; ?></div></form>
  <?php if ($id) : ?><div class="row g-3"><div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECAROTASKS_CHECKLIST'); ?></strong></div><div class="card-body"><ul class="list-group mb-3"><?php foreach ((array) ($this->task['checklist'] ?? []) as $item) : ?><li class="list-group-item d-flex justify-content-between align-items-center"><span><?php echo !empty($item['is_done']) ? '✓ ' : ''; ?><?php echo htmlspecialchars((string) $item['label'], ENT_QUOTES, 'UTF-8'); ?></span><form method="post" action="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.toggleChecklist&id=' . $id . '&item_id=' . (int) $item['id'] . '&done=' . (!empty($item['is_done']) ? '0' : '1')); ?>"><?php echo HTMLHelper::_('form.token'); ?><button class="btn btn-sm btn-outline-secondary" type="submit"><?php echo !empty($item['is_done']) ? Text::_('COM_XDECAROTASKS_REOPEN') : Text::_('COM_XDECAROTASKS_DONE'); ?></button></form></li><?php endforeach; ?></ul><form method="post" action="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.addChecklist&id=' . $id); ?>" class="d-flex gap-2"><input name="label" class="form-control" required maxlength="500" placeholder="<?php echo Text::_('COM_XDECAROTASKS_CHECKLIST_ADD'); ?>"><?php echo HTMLHelper::_('form.token'); ?><button class="btn btn-secondary" type="submit">+</button></form></div></div></div><div class="col-12 col-lg-6"><div class="card h-100"><div class="card-header"><strong><?php echo Text::_('COM_XDECAROTASKS_COMMENTS'); ?></strong></div><div class="card-body"><div class="vstack gap-2 mb-3"><?php foreach ((array) ($this->task['comments'] ?? []) as $comment) : ?><div class="border rounded p-2"><div><?php echo nl2br(htmlspecialchars((string) $comment['body'], ENT_QUOTES, 'UTF-8')); ?></div><small class="text-body-secondary"><?php echo htmlspecialchars((string) $comment['created_at'], ENT_QUOTES, 'UTF-8'); ?></small></div><?php endforeach; ?></div><form method="post" action="<?php echo Route::_('index.php?option=com_xdecarotasks&task=task.addComment&id=' . $id); ?>"><textarea name="body" class="form-control mb-2" required rows="3"></textarea><?php echo HTMLHelper::_('form.token'); ?><button class="btn btn-secondary" type="submit"><?php echo Text::_('COM_XDECAROTASKS_COMMENT_ADD'); ?></button></form></div></div></div><div class="col-12"><div class="card"><div class="card-header"><strong><?php echo Text::_('COM_XDECAROTASKS_HISTORY'); ?></strong></div><div class="table-responsive"><table class="table table-sm mb-0"><tbody><?php foreach ((array) ($this->task['history'] ?? []) as $row) : ?><tr><td><?php echo htmlspecialchars((string) $row['created_at'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars((string) $row['action'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo (int) $row['actor_user_id']; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div><?php endif; ?>
</div>
